# Generated by Django 4.2 on 2023-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('premier_date', models.DateField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.DurationField()),
                ('actors', models.ManyToManyField(related_name='acted_in', to='movies.person')),
                ('directors', models.ManyToManyField(related_name='directed', to='movies.person')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('writers', models.ManyToManyField(related_name='wrote', to='movies.person')),
            ],
        ),
    ]
